Update repository method updateExpiryStatus to run only if Product table exists
This was done to fix the following error (taken from catalina.out):

Updating Product Expiry Status
Hibernate: update Product set status=? where status=? and expiresOn<?
11:43:11,402  WARN SqlExceptionHelper:143 - SQL Error: 1146, SQLState:
42S02
11:43:11,403 ERROR SqlExceptionHelper:144 - Table 'v2v_new.product'
doesn't exist
11:43:11,406 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error
occurred in scheduled task.
javax.persistence.PersistenceException:
org.hibernate.exception.SQLGrammarException: Table 'v2v_new.product'
doesn't exist
	at
org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManage
rImpl.java:1377)
	at
org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManage
rImpl.java:1300)
	at
org.hibernate.ejb.AbstractEntityManagerImpl.throwPersistenceException(Ab
stractEntityManagerImpl.java:1387)
	at
org.hibernate.ejb.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java
:108)
	at
repository.ProductRepository.updateExpiryStatus(ProductRepository.java:5
65)
	at
repository.ProductRepository$$FastClassByCGLIB$$ecfba3d5.invoke(<generat
ed>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at
org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.i
nvokeJoinpoint(Cglib2AopProxy.java:689)
	at
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(Ref
lectiveMethodInvocation.java:150)
	at
org.springframework.transaction.interceptor.TransactionInterceptor.invok
e(TransactionInterceptor.java:110)
	at
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(Ref
lectiveMethodInvocation.java:172)
	at
org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedIntercept
or.intercept(Cglib2AopProxy.java:622)
	at
repository.ProductRepository$$EnhancerByCGLIB$$38521480.updateExpiryStat
us(<generated>)
	at tasks.ProductExpiryChecker.run(ProductExpiryChecker.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.jav
a:39)
	at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessor
Impl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at
org.springframework.scheduling.support.ScheduledMethodRunnable.run(Sched
uledMethodRunnable.java:64)
	at
org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.r
un(DelegatingErrorHandlingRunnable.java:53)
	at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at
java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:31
7)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150)
	at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.acc
ess$101(ScheduledThreadPoolExecutor.java:98)
	at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run
Periodic(ScheduledThreadPoolExecutor.java:180)
	at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run
(ScheduledThreadPoolExecutor.java:204)
	at
java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecuto
r.java:895)
	at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.ja
va:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: org.hibernate.exception.SQLGrammarException: Table
'v2v_new.product' doesn't exist
	at
org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExc
eptionTypeDelegate.java:82)
	at
org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(S
tandardSQLExceptionConverter.java:49)
	at
org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHel
per.java:125)
	at
org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHel
per.java:110)
	at
org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.c
ontinueInvocation(AbstractStatementProxyHandler.java:129)
	at
org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(Abs
tractProxyHandler.java:81)
	at com.sun.proxy.$Proxy56.executeUpdate(Unknown Source)
	at
org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.
java:95)
	at
org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTr
anslatorImpl.java:413)
	at
org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQuer
yPlan.java:282)
	at
org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1268)
	at org.hibernate.internal.QueryImpl.executeUpdate(QueryImpl.java:116)
	at
org.hibernate.ejb.QueryImpl.internalExecuteUpdate(QueryImpl.java:188)
	at
org.hibernate.ejb.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java
:99)
	... 25 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException:
Table 'v2v_new.product' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native
Method)
	at
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorA
ccessorImpl.java:39)
	at
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingCons
tructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at
com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:
2155)
	at
com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:24
58)
	at
com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:23
75)
	at
com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:23
59)
	at
com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProx
yPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
	at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessor
Impl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at
org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.c
ontinueInvocation(AbstractStatementProxyHandler.java:122)
	... 34 more